# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'composeApp', :path => '../composeApp'

  # Pod for your KMP shared module.
  # The path should point to the directory containing your shared module's build.gradle.kts
  # and the cocoapods block. Gradle will generate the .podspec file in that location.
  pod 'shared', :path => '../shared'

  pod 'GoogleMaps', '9.0.0'
  pod 'Google-Maps-iOS-Utils', '6.1.0'

end
